### ISSUE TITLE
Getting the list of appropriate sales reports

### ISSUE THREAD

**Issue by chadius-maximus** [GodTamIt/shop_with_friends_forreal#1]
I have a trouble getting the list of appropriate sales reports, I am  99% percent sure that it has to do with async, just like the last time. GetAllPosts was sync, so no problems there. Measures I took in attempts to make it works can be seen in onCreate in HomeActivity

**Comment by GodTamIt** [comment]
Resolved in latest commit in branch 'oleg'. Database primary key error.
